### PR TITLE
Recommender summarizing or reflective filtering

### PR DESCRIPTION
**Pull request by pety-dc**
Originally when a token had a contact_id, the recommender automatically filtered the `recommender_event_log` to that contact. This resulted that a recommender could only recommend items that a contact already done something with (event)

That's a `reflective` working mechanism which can be useful for a `abandoned basket` scenario.

`Exclusive` filtering mechanism excludes the current user from the recommender query. This results that the query searches only in other contacts events. Possible scenario is "most popular item". "most recently bought item"

`Inclusive` filtering mechanism searches bith in the contacts and other contacts events.

### CODE REVIEW

**Comment by kuzmany** [comment]
Nice PR
What is proximity filtering?

**Comment by pety-dc** [comment]
`Proximity` is an experimental solution. It has precision of 5 and 10.
It takes the most relevant (based on sum weight) 5/10 items for the target Contact from the past 5/10 weeks
Then takes the most relevant (based on sum weight) 5/10 contacts for the previous items from the past 5/10 weeks

And finally runs the query now with the filter settings and also filters to the 5/10 contacts from above.

It based on some kind of basic & loose similarity in interest and temporality

**Comment by kuzmany** [comment]
Please resolve conflicts.

**Comment by pety-dc** [comment]
resolved

**Pull request merged**
