### PR TITLE
Setup import paramaters plugin settings2

### PR DESCRIPTION
**Pull request by pety-dc**
Setup import paramaters plugin settings2
- items url
- events url
- batch size
- timeout

command parameter priority:
- command parameter
- plugin setting
- hard coded default

### CODE REVIEW

**Comment by kuzmany** [comment]
I avoid made this configuration, because for non tech people are not under understandable.
This settings can setup by agency or 3rd party tool. 

Are you sure it's necessary add it to core? Non tech people were mad from that.

**Comment by pety-dc** [comment]
I understand your reasons. 

We operate multiple mautic instances. Clients have different needs and understanding and doing these settings puts heavier responsibilities on agency/support people as they need to know more, but on the other hand we try to minimize setting type tasks done by developers.

I thought plugin settings already consist of semi-technical info it won't bother non-tech people. But having those settings in the plugin settings enables agency/support people, or the client to fine-tune from what url the catalogue is downloaded, and how often are items updated based on needs (eg stock)

**Comment by kuzmany** [comment]
@pety-dc 
Ok, I am going to merge it.
Can you resolve conflicts?

**Comment by pety-dc** [comment]
I resolved the conflicts

**Pull request merged**
